### PR TITLE
Add makefile target to check vendor

### PR DESCRIPTION
**Pull request by bn222**

### CODE REVIEW

**Comment by wizhaoredhat** [comment]
Nice!
/lgtm

**Comment by SalDaniele** [comment]
First prow-triggered successful e2e test! https://net-hw-ci-jenkins-csb-nst.apps.ocp-c1.prod.psi.redhat.com/view/IPU%20Testing/job/99_E2E_IPU_Deploy/175/console

```
Results of POD_TO_POD_SAME_NODE-SRIOV_TO_POD_IP_TO_SRIOV-SAME_NODE: success
  Total GBytes: 21.3042 GBytes
  Average Bitrate: 6.10 Gbits/s
  Average Jitter: 0.000822177 ms
  Total Lost Packets: 1240394
  Total Lost Percent: 7.85%
```

**Comment by SalDaniele** [comment]
Passed e2e test w/ tft validation: https://net-hw-ci-jenkins-csb-nst.apps.ocp-c1.prod.psi.redhat.com/view/IPU%20Testing/job/99_E2E_IPU_Deploy/174/console

**Pull request merged**
