### PR TITLE
bump cda

### PR DESCRIPTION
**Pull request by bn222**

### CODE REVIEW

**Comment by bn222** [comment]
/unhold

If it passes, CI we can merge in CDA too. I'm currently building mev ts 1.8 support on top.

**Comment by SalDaniele** [comment]
e2e test passed: https://net-hw-ci-jenkins-csb-nst.apps.ocp-c1.prod.psi.redhat.com/view/IPU%20Testing/job/99_E2E_IPU_Deploy/79/console

**Pull request merged**
