### PR TITLE
To test set IP VSP change, commit in VSP repo.

### PR DESCRIPTION
**Pull request by sudhar-krishnakumar**
To test set IP VSP change, commit in VSP repo.

### CODE REVIEW

**Comment by sudhar-krishnakumar** [comment]
@SalDaniele can you trigger CI test, with ok-to-test

**Comment by SalDaniele** [comment]
/lgtm

Thanks @sudhar-krishnakumar !

**Comment by SalDaniele** [comment]
After inspecting the cluster this CI test ran on manually, I can see the comm channel interface is up as expected, and I was able to start an sriov pod on the host.

I think the failure now is due to the dpu operator / vsp pods taking significant time to get into a "ready" state.

Trying to add back a sleep in https://github.com/openshift/dpu-operator/pull/199

**Comment by SalDaniele** [comment]
@sudhar-krishnakumar We can close this, these commits were added in a separate PR

**Pull request closed without merging**
