### PR TITLE
update ghw to allow running without internet

### PR DESCRIPTION
**Pull request by bn222**

### CODE REVIEW

**Comment by bn222** [comment]
@sudhar-krishnakumar please test this behind a proxy.
/hold

**Comment by wizhaoredhat** [comment]
We need this change in pcidb https://github.com/jaypipes/pcidb/commit/7cd2fadac2d9852fa9b5e87875ba0d121fc4a082 
To be able to run in disconnected environments . @bn222 Could you please add this in the commit message?

**Comment by bn222** [comment]
Needs more work, use "set env var"-workaround in the meanwhile.

**Comment by SalDaniele** [comment]
Already passed, retested due to prow bug: https://net-hw-ci-jenkins-csb-nst.apps.ocp-c1.prod.psi.redhat.com/view/IPU%20Testing/job/99_E2E_IPU_Deploy/157/parameters/

**Comment by SalDaniele** [comment]
Maybe have overridden pre-maturely, this causes failure when starting dpu daemon:

`(ocp-venv) [root@wsfd-advnetlab239 dpu-operator]# oc logs -n openshift-dpu-operator     dpu-daemon-kwsbr                                                                                                                          
2024-10-16T18:12:23Z    INFO    Daemon Init     Daemon init                                                                                                                                                                       
2024-10-16T18:12:23Z    INFO    Daemon Init     Detected OpenShift      {"flavour": "MicroShift"}                                                                                                                                 
2024-10-16T18:12:23Z    INFO    Daemon Init     Prepared CNI binary     {"path": "/opt/cni/bin/dpu-cni"}                                                                                                                          
2024-10-16T18:12:23Z    ERROR   Daemon Init     Failed to parse mode    {"error": "Failed to query platform info: Failed to detect DPU platform: Error getting product info: No pci-ids DB files found (and network fetch disabled
)"}                                                                                                                                                                                                                               
main.main                                                                                                                                                                                                                         
        /workspace/cmd/daemon/daemon.go:161                                                                                                                                                                                       
runtime.main                                                                                                                                                                                                                      
        /usr/lib/golang/src/runtime/proc.go:271     `
        
Investigating

**Pull request merged**
