### PR TITLE
Run tests 5 times

### PR DESCRIPTION
**Pull request by bn222**

### CODE REVIEW

**Comment by wizhaoredhat** [comment]
Why do we want to run it so many times?

**Comment by SalDaniele** [comment]
First prow-triggered successful e2e test! https://net-hw-ci-jenkins-csb-nst.apps.ocp-c1.prod.psi.redhat.com/view/IPU%20Testing/job/99_E2E_IPU_Deploy/175/console

```
Results of POD_TO_POD_SAME_NODE-SRIOV_TO_POD_IP_TO_SRIOV-SAME_NODE: success
  Total GBytes: 21.3042 GBytes
  Average Bitrate: 6.10 Gbits/s
  Average Jitter: 0.000822177 ms
  Total Lost Packets: 1240394
  Total Lost Percent: 7.85%
```

**Comment by bn222** [comment]
> Why do we want to run it so many times?

To decrease the likelihood of changes that work sometimes passing in the CI. We can also increase it to more than 5.

**Comment by bn222** [comment]
@wizhaoredhat for example: https://github.com/openshift/dpu-operator/commit/f0ecb6c8540bf259959298c942fd1d487ca87fbc

Should have been caught

**Comment by SalDaniele** [comment]
/override ci/prow/make-e2e-test

This has passed twice, the failure is do to a bug I introduced in a post step to capture cluster logs: https://net-hw-ci-jenkins-csb-nst.apps.ocp-c1.prod.psi.redhat.com/view/IPU%20Testing/job/99_E2E_IPU_Deploy/193/console

**Pull request merged**
