### PR TITLE
OCPBUGS-38580: [4.17] Bump manifests to 4.17

### PR DESCRIPTION
**Pull request by locriandev**
Successfully created task: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=63418243

### CODE REVIEW

**Comment by locriandev** [comment]
@wizhaoredhat do you know who can get the missing label in? Everything is ready to get dpu-operator re-enabled in 4.17 too. Builds are flowing again in 4.18 (see [dpu-operator-container-v4.18.0-202408191846.p0.ga8bae13.assembly.stream.el9](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=3234116))

**Comment by wizhaoredhat** [comment]
@zhaozhanqi @yingwang-0320  Could you please add cherry-pick-approved label?

**Pull request merged**
